package com.servlets;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import org.owasp.esapi.ESAPI;
import com.beans.BookBean;
import com.beans.IssueBookBean;
import com.dao.BookDao;

//URL annotation
@WebServlet("/ViewIssuedBook")
public class ViewIssuedBook extends HttpServlet {
	
	//Servlet that displays all the Issued books to students from database. It calls Dao function to retreive all the issued books from database and uses loop to display in table.
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		
		//Session tracking
				HttpSession session = request.getSession();
				if (session != null) {
					if (session.getAttribute("email") != null) {
						String name = (String) session.getAttribute("email");
						
					} else {
						response.sendRedirect("index.jsp");
					}
				}
		
		response.setContentType("text/html");
		PrintWriter out=response.getWriter();
		
		out.print("<!DOCTYPE html>");
		out.print("<html>");
		out.println("<head>");
		out.println("<title>View Librarian</title>");
		out.println("<link rel='stylesheet' href='styles/main.css'/>");
		out.println("</head>");
		out.println("<body>");
		
		request.getRequestDispatcher("viewbook.jsp").include(request, response);
		List<IssueBookBean> list=BookDao.viewIssuedBooks();
		
		out.println("<table class='beta'>");

		out.println("<tr><th>Callno</th><th>Student Id</th><th>Librarian Id</th><th>Issued Date</th><th>Return Status</th></tr>");
		for(IssueBookBean bean:list){
			// 1 NOTE: code generated by ESIDE to prevent XSS attack
                  out.println("<tr><td>" + ESAPI.encoder().encodeForHTMLAttribute(bean.getAileno()) + "</td><td>"
					+ bean.getStudentid() + "</td><td>"
					+ bean.getLibrarianid() + "</td><td>"
					+ bean.getIssueddate() + "</td><td>"
					+ ESAPI.encoder().encodeForHTMLAttribute(bean.getReturnstatus()) + "</td></tr>");
		}
		out.println("</table>");
		
		out.println("</div>");
		out.close();
	}
}
